
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 03:35:35 +07 (Nov 18 2025 20:35:35 UTC)

// Verification Directory fv/not1 

module not1(A, Y);
  input A;
  output Y;
  wire A;
  wire Y;
  INVXLLVT g2(.A (A), .Y (Y));
endmodule

