
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 21:21:51 +07 (Nov 20 2025 14:21:51 UTC)

// Verification Directory fv/full_adder 

module full_adder(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1LVT g85__2398(.A (B), .B (A), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

