
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 04:38:14 +07 (Nov 18 2025 21:38:14 UTC)

// Verification Directory fv/or2 

module or2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  OR2XLHVT g2__2398(.A (B), .B (A), .Y (Y));
endmodule

