
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 01:15:44 +07 (Nov 19 2025 18:15:44 UTC)

// Verification Directory fv/mux 

module mux(A, B, S, Y);
  input A, B, S;
  output Y;
  wire A, B, S;
  wire Y;
  MX2XLLVT g32__2398(.A (A), .B (B), .S0 (S), .Y (Y));
endmodule

