
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 21:48:59 +07 (Nov 19 2025 14:48:59 UTC)

// Verification Directory fv/nand2 

module nand2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NAND2XLLVT g4__2398(.A (B), .B (A), .Y (Y));
endmodule

