
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 16 2025 13:52:14 +07 (Nov 16 2025 06:52:14 UTC)

// Verification Directory fv/and2 

module and2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  AND2XLLVT g11__2398(.A (B), .B (A), .Y (Y));
endmodule

