
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 22:51:24 +07 (Nov 19 2025 15:51:24 UTC)

// Verification Directory fv/nor2 

module nor2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NOR2XLLVT g13__2398(.A (B), .B (A), .Y (Y));
endmodule

