
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 21 2025 15:11:40 +07 (Nov 21 2025 08:11:40 UTC)

// Verification Directory fv/dff 

module dff(clk, D, Q);
  input clk, D;
  output Q;
  wire clk, D;
  wire Q;
  DFFHQX1HVT Q_reg(.CK (clk), .D (D), .Q (Q));
endmodule

